name = "LowDiscrepancySequences"
uuid = "a8b5c6d0-1234-5678-9abc-def012345678"
version = "0.1.0"
authors = ["Plurigrid ASI"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Colors = "0.13.1"
